# Generated by Django 5.2.14 on 2026-05-10 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_policy_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyitem',
            name='max_percent_of_policy',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
